#!/bin/sh

EDITOR="nvim"
edt() {
	case "$1" in
		astro)
			$EDITOR ~/.config/EDITOR/lua/user/
			;;

		i3)
			$EDITOR ~/.config/i3/config
			;;
		bashrc)
			$EDITOR ~/.bashrc
			;;
		picom)
			$EDITOR ~/.config/picom/picom.conf
			;;
		*)
			echo "edt: unknown keyword '$1'"
	esac
}

complete -W "astro i3 bashrc picom" edt
