#!/bin/sh

# プログラムの絶対パス
ABSPATH_OF_PROG=$0

# 移動するためのパス
CD_PATH="${ABSPATH_OF_PROG%/*}"

# プログラム名
PROG_NAME=$(basename $ABSPATH_OF_PROG)

# /unix_toolsets ディレクトリへ移動
cd $CD_PATH

# file コマンドによって(このプログラムは除く) executable なものだけを表示する
file * | grep executable | awk '{print $1}' | tr ":" " " | grep -v $PROG_NAME
