#!/bin/sh

if [ "$#" != "4" ]; then
        echo "usage:"
        echo "          [+] mknt <book_title> <chapter_num> <make code dir? t or f> <make memo? t or f>"
        exit 0
fi

mkdir $1
cd $1  

if [ "$2" != "0" ]; then
        for chapter_num in $(seq 0 $(($2-1))); do
                mkdir chapter_$((chapter_num+1))

                if [ "$3" = "t" ]; then
                        mkdir ./chapter_$((chapter_num+1))/code
                fi

                if [ "$4" = "t" ]; then
                        touch ./chapter_$((chapter_num+1))/chapter_$((chapter_num+1))
                fi
        done
fi
