#!/bin/sh

if [ "$#" != "2" ]; then
        echo "usage:"
        echo "          [+] mklib <book_title> <chapter_num>"
        exit 0
fi

mkdir $1
cd $1  

if [ "$2" != "0" ]; then
        for chapter_num in $(seq 0 $(($2-1))); do
                mkdir chapter_$((chapter_num+1))
                touch ./chapter_$((chapter_num+1))/chapter_$((chapter_num+1))
        done
fi
