#!/bin/sh

if [ "$1" = "rust" ]; then
        cd ~/Projects/Rust/ && nvim
elif [ "$1" = "c" ]; then
	cd ~/Projects/C/ && nvim
elif [ "$1" = "nvim-config" ]; then
        cd ~/.config/nvim/lua/user/ && nvim
elif [ "$1" = "i3-config" ]; then
        cd ~/.config/i3/ && nvim config
elif [ "$1" = "univ" ]; then
        cd ~/Projects/Univ/ && nvim
else
        echo "usage:"
        echo "          [+] open rust        : then open rust project directory"
        echo "          [+] open c           : then open c project directory"
	echo "          [+] open nvim-config : then open nvim config file"
	echo "          [+] open i3-config   : then open i3wm config file"
	echo "          [+] open univ        : then open univ directory"
fi
