#!/bin/sh

if [ "$1" = "nvim-config" ]; then
        cd ~/.config/nvim/lua/user/ && nvim
elif [ "$1" = "i3-config" ]; then
        cd ~/.config/i3/ && nvim config
else
        echo "usage:"
	echo "          [+] open nvim-config : then open nvim config file"
	echo "          [+] open i3-config   : then open i3wm config file"
fi
