#!/bin/sh

if [ "$1" = "-y" ]; then
        echo y | sudo pacman -Syu

elif [ "$1" = "-s" ]; then
        sudo pacman -Syu

else 
        echo "usage:"
        echo "          [+] upgrade -y : Auto update"
        echo "          [+] upgrade -s : See updatable packages"
fi
